"""Trade selector.

Pipeline:
1. Take Grok's candidate trades.
2. Hydrate from chain data (real Greeks/IV/volume; never estimated).
3. Compute payoff metrics (Black-76 + payoff_engine).
4. Run sizing.
5. Pass to risk_engine.validate_trade().
6. Pass *accepted* trades through Opus validator. Opus must "accept" or
   "revise"; "reject" flips to NO TRADE with the validator's reason.

Each slot independently can return NO TRADE.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass

from app.analysis.option_pricing import black76
from app.analysis.payoff_engine import metrics_for_structure
from app.analysis.risk_engine import RiskRejection, validate_trade
from app.analysis.sizing import size_spread, size_yolo
from app.config import get_settings
from app.data.llm_client import OpusValidator, parse_json_or_empty
from app.models.headline import HeadlineCluster
from app.models.macro_signal import RegimeAssessment, Regime
from app.models.option_contract import OptionChain, OptionType
from app.models.trade_idea import (
    NoTradeReason,
    SpreadStructure,
    TradeIdea,
    TradeKind,
    TradeLeg,
    ValidatorVerdict,
)

log = logging.getLogger(__name__)


@dataclass
class SlotResult:
    trade: TradeIdea | None
    no_trade_reason: NoTradeReason | None = None
    detail: str = ""


@dataclass
class SelectorOutput:
    spread: SlotResult
    yolo: SlotResult
    rejected: list[dict]
    convergence: list[str]
    dissent: list[str]
    executive_read: list[str]
    regime_explanation: str
    model_primary: str
    model_validator: str


VALIDATOR_SYSTEM = """\
You are Claude Opus, acting as the adversarial validator for a macro options
trade idea generated by a primary LLM. Your job is to challenge and fact-check
the trade across four dimensions:

1. NEWS — are the cited headlines plausible / consistent with the supplied
   corpus? Flag fabricated sources, contradictions, or mis-attributions.
2. TRADE THEORY — is the causal chain coherent (headline -> policy/liquidity
   -> asset -> option expression)? Reject hand-waving, magical thinking,
   reflexivity assumed without evidence.
3. RISK / REWARD — for spreads, does max_gain/max_loss truly clear 2.0 at
   expiration given the supplied legs and premiums? For YOLO, is premium
   capped, is the breakeven plausible? No naked shorts ever.
4. OPTION STRATEGY — does the structure actually express the thesis cleanly,
   given liquidity, Greeks, time horizon? Defined-risk spread when drift, not
   shock; YOLO single long when convex tail wanted.

Return JSON ONLY:

{
  "decision": "accept" | "revise" | "reject",
  "news_check": "...",
  "trade_theory_check": "...",
  "risk_reward_check": "...",
  "option_strategy_check": "...",
  "issues": ["..."],
  "revisions_suggested": ["..."],
  "confidence": 0.0..1.0
}

Be rigorous. If anything is wrong, say so. If the trade is sound, say "accept".
"""


def _hydrate_trade(slot: str, candidate: dict, chain: OptionChain) -> TradeIdea:
    """Turn Grok's candidate into a TradeIdea using real chain data."""
    legs_in = candidate["legs"]
    hydrated_legs: list[TradeLeg] = []
    for leg in legs_in:
        ot = OptionType(leg["option_type"])
        contract = chain.find(float(leg["strike"]), ot)
        if contract is None:
            raise RiskRejection(NoTradeReason.MISSING_CHAIN_DATA,
                                f"strike {leg['strike']}{leg['option_type']} not in chain")
        # use chain mid for premium so we don't carry a fabricated price
        premium = round(contract.mid, 6)
        hydrated_legs.append(TradeLeg(
            action=leg["action"],
            quantity=int(leg.get("quantity", 1)),
            option_type=ot,
            strike=contract.strike,
            expiration=contract.expiration,
            premium=premium,
            iv=contract.iv,
            delta=contract.delta,
            gamma=contract.gamma,
            theta=contract.theta,
            vega=contract.vega,
        ))

    structure = SpreadStructure(candidate["structure"])
    metrics = metrics_for_structure(structure, hydrated_legs)
    multiplier = chain.multiplier
    max_loss_dollars = metrics.max_loss * multiplier
    max_profit_dollars = metrics.max_profit * multiplier if metrics.max_profit != float("inf") else 1e9

    rr = (max_profit_dollars / max_loss_dollars) if max_loss_dollars > 0 else 0.0

    kind = TradeKind.YOLO_LONG if slot == "yolo" else TradeKind.DEFINED_RISK_SPREAD
    if slot == "spread":
        sizing = size_spread(max_loss_dollars)
    else:
        sizing = size_yolo(max_loss_dollars)

    trade = TradeIdea(
        kind=kind,
        name=candidate["name"],
        root=chain.root,
        underlying_symbol=chain.underlying_symbol,
        direction=candidate.get("direction", "neutral"),
        structure=structure,
        expiration=chain.expiration,
        legs=hydrated_legs,
        entry_debit_credit=metrics.net_debit,
        max_loss=max_loss_dollars,
        max_profit=max_profit_dollars,
        breakeven=metrics.breakeven,
        rr_ratio=rr,
        bid_ask_pct_worst=0.0,                # filled by risk_engine
        min_volume=0,
        min_open_interest=0,
        catalyst=candidate.get("catalyst", ""),
        causal_chain=candidate.get("causal_chain", ""),
        why_this_structure=candidate.get("why_this_structure", ""),
        what_kills_thesis=candidate.get("what_kills_thesis", ""),
        why_probably_dumb=candidate.get("why_probably_dumb"),
        invalidation=candidate.get("invalidation", candidate.get("what_kills_thesis", "")),
        stop_logic=candidate.get("stop_logic", "Exit if causal chain breaks (catalyst priced or invalidated)."),
        profit_taking_logic=candidate.get("profit_taking_logic", "Scale at 50%/75% of max profit; close into expiry week."),
        suggested_contracts=sizing.contracts,
        risk_dollars=sizing.risk_dollars,
        sizing_note=sizing.note,
    )
    return trade


def _validate_with_opus(trade: TradeIdea, clusters: list[HeadlineCluster]) -> ValidatorVerdict:
    s = get_settings()
    if s.mock_data or not s.anthropic_api_key:
        return ValidatorVerdict(
            decision="accept",
            news_check="Headlines align with fixture corpus.",
            trade_theory_check="Causal chain is internally consistent.",
            risk_reward_check=f"Spread/YOLO math sane; rr_ratio={trade.rr_ratio:.2f}.",
            option_strategy_check="Structure matches thesis (drift => spread; tail => YOLO).",
            issues=[],
            revisions_suggested=[],
            confidence=0.78,
        )
    validator = OpusValidator(s)
    cluster_corpus = [
        {
            "name": c.name, "channel": c.channel,
            "headlines": [{"title": h.title, "source": h.source, "tier": h.tier.value,
                            "url": str(h.url)} for h in c.headlines]
        } for c in clusters
    ]
    user = json.dumps({
        "trade": json.loads(trade.model_dump_json()),
        "headline_corpus": cluster_corpus,
    }, default=str)
    resp = validator.critique(VALIDATOR_SYSTEM, user)
    parsed = parse_json_or_empty(resp.text)
    if not parsed:
        return ValidatorVerdict(
            decision="revise",
            news_check="validator response unparseable",
            trade_theory_check="",
            risk_reward_check="",
            option_strategy_check="",
            issues=["validator returned non-JSON"],
            confidence=0.0,
        )
    return ValidatorVerdict(**parsed)


def select_trades(
    *,
    regime: RegimeAssessment,
    clusters: list[HeadlineCluster],
    chains_by_root: dict[str, OptionChain],
    candidate_trades: list[dict],
    model_primary: str,
    executive_read: list[str],
    convergence: list[str],
    dissent: list[str],
) -> SelectorOutput:
    """Hydrate, risk-check, validate. Per-slot NO TRADE on any failure."""

    s = get_settings()
    rejected: list[dict] = []

    # Regime-level no-signal short circuit.
    if regime.regime == Regime.NO_SIGNAL:
        return SelectorOutput(
            spread=SlotResult(trade=None, no_trade_reason=NoTradeReason.REGIME_NO_SIGNAL,
                              detail="Regime classified as no_signal / range-bound."),
            yolo=SlotResult(trade=None, no_trade_reason=NoTradeReason.REGIME_NO_SIGNAL,
                            detail="Regime classified as no_signal / range-bound."),
            rejected=rejected,
            convergence=convergence,
            dissent=dissent,
            executive_read=executive_read,
            regime_explanation=regime.explanation,
            model_primary=model_primary,
            model_validator=s.anthropic_model if not s.mock_data else "opus-mock",
        )

    spread_result = SlotResult(trade=None, no_trade_reason=NoTradeReason.WEAK_SIGNAL,
                                detail="No spread candidate produced.")
    yolo_result = SlotResult(trade=None, no_trade_reason=NoTradeReason.WEAK_SIGNAL,
                              detail="No YOLO candidate produced.")

    for cand in candidate_trades:
        slot = cand.get("slot")
        root = cand.get("root", "").upper()
        chain = chains_by_root.get(root)
        if chain is None:
            rejected.append({"name": cand.get("name", root), "reason": "missing chain"})
            slot_target = spread_result if slot == "spread" else yolo_result
            slot_target.no_trade_reason = NoTradeReason.MISSING_CHAIN_DATA
            slot_target.detail = f"no chain for {root}"
            continue

        try:
            trade = _hydrate_trade(slot, cand, chain)
            trade = validate_trade(trade, chain)
        except RiskRejection as e:
            rejected.append({"name": cand.get("name", "?"), "reason": e.reason.value, "detail": e.detail})
            slot_target = spread_result if slot == "spread" else yolo_result
            slot_target.no_trade_reason = e.reason
            slot_target.detail = e.detail
            continue
        except Exception as e:                              # validator/Pydantic/etc.
            rejected.append({"name": cand.get("name", "?"), "reason": "validation_error", "detail": str(e)})
            slot_target = spread_result if slot == "spread" else yolo_result
            slot_target.no_trade_reason = NoTradeReason.NO_CLEAN_EXPRESSION
            slot_target.detail = str(e)
            continue

        # --- Opus validator ---
        verdict = _validate_with_opus(trade, clusters)
        trade = trade.model_copy(update={
            "validator_verdict": verdict,
            "model_primary": model_primary,
            "validator_model": s.anthropic_model if not s.mock_data else "opus-mock",
        })

        if verdict.decision == "reject":
            rejected.append({"name": trade.name, "reason": "validator_rejected", "detail": "; ".join(verdict.issues)})
            slot_target = spread_result if slot == "spread" else yolo_result
            slot_target.no_trade_reason = NoTradeReason.VALIDATOR_REJECTED
            slot_target.detail = "; ".join(verdict.issues) or "Opus rejected"
            continue

        if slot == "spread":
            spread_result = SlotResult(trade=trade)
        elif slot == "yolo":
            yolo_result = SlotResult(trade=trade)

    return SelectorOutput(
        spread=spread_result,
        yolo=yolo_result,
        rejected=rejected,
        convergence=convergence,
        dissent=dissent,
        executive_read=executive_read,
        regime_explanation=regime.explanation,
        model_primary=model_primary,
        model_validator=s.anthropic_model if not s.mock_data else "opus-mock",
    )
